# Generated by Django 5.2 on 2025-04-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('feedback_type', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], default='Positive', max_length=8)),
                ('feedback_time', models.DateTimeField(auto_now_add=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
